parameters:
    myonlinestore_rabbitmq_manager.config_generator.class: MyOnlineStore\Bundle\RabbitMqManagerBundle\Generator\RabbitMqConfigGenerator
    phobetor_rabbitmq_supervisor.supervisor_service.class: MyOnlineStore\Bundle\RabbitMqManagerBundle\Supervisor\Supervisor

services:
    myonlinestore_rabbitmq_manager.config_generator:
        class: "%myonlinestore_rabbitmq_manager.config_generator.class%"
        arguments:
            - "@templating"
            - "%mos_rabbitmq_cli_consumer.config%"

    myonlinestore_rabbitmq_manager.supervisor:
        class: "%phobetor_rabbitmq_supervisor.supervisor_service.class%"
        arguments:
            - "%mos_rabbitmq_cli_consumer.config%"
